name: deploy-azureopenaidemo

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  lint-aas-bicep:
    uses: ./.github/workflows/lint-aas-bicep.yml

  build-blazorserver:
    uses: ./.github/workflows/build-blazorserver.yml

  deploy-aas:
    if: vars.Type == 'AAS'
    needs:
      - lint-aas-bicep
      - build-blazorserver
    uses: ./.github/workflows/deploy-aas.yml
    with:
      LOCATION: ${{ vars.LOCATION }}
      BASE_RESOURCE_NAME: ${{ vars.BASE_RESOURCE_NAME }}
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      APPSERVICEPLAN_CONFIGURATION: ${{ vars.APPSERVICEPLAN_CONFIGURATION }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
